# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: merubokkusu
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.paypal.me/merubokkusu','https://cash.app/$Merubokkusu','https://steamcommunity.com/tradeoffer/new/?partner=94720138&token=GY23F7tU', 'https://www.blockchain.com/btc/payment_request?address=1CEfCSYG8XbLfdvMJA8BfL1oT47CpFwRjP&message=arandomnewaccount&amount=0.00008546']
